[versions]
agp = "8.13.2"
barcodeScanning = "17.1.0"
cameraCamera2 = "1.3.0"
cameraCore = "1.3.0"
commonsCodec = "1.15"
core = "3.5.3"
gson = "2.10.1"
appcompat = "1.7.1"
kotlinOnetimepassword = "2.0.1"
material = "1.13.0"
firebaseCrashlyticsBuildtools = "3.0.6"
cameraView = "1.5.2"
cameraLifecycle = "1.5.2"
slidableactivity = "2.1.0"

[libraries]
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCamera2" }
barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanning" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraCore" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commonsCodec" }
core = { module = "com.google.zxing:core", version.ref = "core" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-onetimepassword = { module = "dev.turingcomplete:kotlin-onetimepassword", version.ref = "kotlinOnetimepassword" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraView" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraLifecycle" }
slidableactivity = { module = "com.r0adkll:slidableactivity", version.ref = "slidableactivity" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

